"""add error field

Revision ID: 5fd3f50147cb
Revises: 92d11f8ca30f
Create Date: 2021-05-10 19:55:29.020060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd3f50147cb'
down_revision = '92d11f8ca30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'error')
    # ### end Alembic commands ###
