"""Initial migration.

Revision ID: eb7bcc2e9c04
Revises: 
Create Date: 2021-04-29 15:45:12.151141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7bcc2e9c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_spec')
    op.drop_table('doctors')
    op.drop_table('doctors_towns')
    op.alter_column('appointments', 'spec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'spec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('doctors_towns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('town_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wp_spec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doctors_towns_pkey')
    )
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('spec_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('town_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('science', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('position', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('stars', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('official_rating', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('rates', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drugrates', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('answers', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('extrainfo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hobby', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('appointment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_owner', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('lpu_pro', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('min_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_price_go', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_price_online', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friendliness', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('osmotr', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('efficiency', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('informativity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('recommend', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('spec_in_title', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('net', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('neg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wp_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_price_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_discount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age_min', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('age_max', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spec_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('honor_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doctors_pkey')
    )
    op.create_table('doctor_spec',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spec_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'spec_id', name='doctor_spec_pkey')
    )
    # ### end Alembic commands ###
