# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: |
          poetry --version
          poetry install
          poetry show
        
      - name: Run linter
        run: flakehell lint

